### ISSUE TITLE
OSError: [Errno 49] Can't assign requested address

### ISSUE THREAD

**Issue by danialfarooq** [jqiang/hls-stream#1]
Hi,
When entering the code into terminal I get [Errno 49]. 

OSTML0253657: hls-stream-master dfa16$ python3 server.py testdata/m1-all_Custom.m3u8 testdata/m2-all_Custom.m3u8 testdata/m3-all_Custom.m3u8
Traceback (most recent call last):
  File "server.py", line 131, in <module>
    main()
  File "server.py", line 127, in main
    print("Watch stream at: http://{}:{}/playlist.m3u8".format(get_ip_address(), port))
  File "server.py", line 96, in get_ip_address
    s.connect(('8.8.8.8', 0))  # connecting to a UDP address doesn't send packets
OSError: [Errno 49] Can't assign requested address

**Comment by JeanCarlosChavarriaHughes** [comment]
Same error.  OsX
